### ISSUE TITLE
Set up monitoring for Ingest components

### ISSUE THREAD

**Issue by rdgoite** [HumanCellAtlas/ingest-central#216] opened 2018-10-10 12:22 UTC
Define metrics and enable monitoring for:
- [ ] Core
- [ ] Importer
- [ ] Exporter

**Comment by justincc** [comment] 2018-11-29 14:34
Seen in https://docs.google.com/spreadsheets/d/155ACGfrgobXy9DI_GduYyHCpkCyFDIa6FvgH8keBdug/edit?ts=5bbbcd2d#gid=0

**Comment by justincc** [comment] 2019-05-21 16:39
Dupe of #369

**Closed by justincc** 2019-05-21 16:39 UTC
Labels: epic
