### ISSUE TITLE
Ingest status indicator in the UI

### ISSUE THREAD

**Issue by morrisonnorman** [HumanCellAtlas/ingest-central#600] opened 2019-10-23 10:46 UTC
## Specific use case or user story:
As a wrangler I would like to see the status of the ingest component in the ingest UI, so that I  know if I can upload a project or dataset.

## Current gap, problem or bottleneck:
Often wranglers go to upload a spreadsheet or data then realise that the ingest component is down or cannot accept parallel submissions.

## Value proposition:
Wranglers are able to quickly determine if the ingest component of the DCP is able to accept submissions via the Ingest UI

## MVP requirements:
Ingest health status in the UI

## Suggester:
@mshadbolt @zperova @ESapenaVentura

**Comment by justincc** [comment] 2019-10-23 11:22
Dupe of #560

**Closed by justincc** 2019-10-23 11:22 UTC
Labels: needs design
