### ISSUE TITLE
Create health check endpoints for components that depend on other services

### ISSUE THREAD

**Issue by danielvaughan** [HumanCellAtlas/ingest-central#43] opened 2018-06-06 15:02 UTC
**What problem does the suggested enhancement solve? Please describe.**

The state tracker depends on Redis and the core MongoDB to function. If connections fail this is not visible.  We should have health check endpoints for these.

**What type of enhancement is this?**

Reliability

**How will this enhancement benefit wrangers and/or end-users?**

Less "not working" errors

**How complex to implement do you estimate this enhancement will be? (High, Medium, Low)**

Medium

**How much benefit do you estimate this enhancement will provide? (High, Medium, Low)**
High

**How urgent is this and is there a specific date it needs to be done by? (High, Medium, Low)**
Medium

**Describe your preferred solution**

An HTTP endpoint for health that can be monitored

**Describe alternatives you've considered**

Some sort of alert or clear log message

**Comment by justincc** [comment] 2019-09-16 16:17
Dupe of #384

**Closed by justincc** 2019-09-16 16:17 UTC
