### ISSUE TITLE
Ability to view example submission to help prepare submission

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/ingest-central#87] opened 2018-08-10 10:49 UTC
**What problem does the suggested enhancement solve? Please describe.**

Current lack of example submissions. As a data contributor, I want to view example submissions in order to understand what information is needed when I prepare my submission.

**What type of enhancement is this?**

Usability

**How will this enhancement benefit wrangers and/or end-users?**

Users will be able to see example submissions to support understanding what information the HCA ingest service needs and how that information should be structured.

**How complex to implement do you estimate this enhancement will be? (High, Medium, Low)**

Low

**How much benefit do you estimate this enhancement will provide? (High, Medium, Low)**

High

**How urgent is this and is there a specific date it needs to be done by? (High, Medium, Low)**

Medium (not for phase 1)

**Describe your preferred solution**

A user is able to access example submissions which illustrate the information required in submissions. This should be supported through UI and API.

**Describe alternatives you've considered**

**Additional context**

Migrated from JIRA: HCA-23.

**Comment by justincc** [comment] 2018-11-26 18:04
Effectively a dupe of #92

**Closed by justincc** 2018-11-26 18:04 UTC
