### ISSUE TITLE
Trigger a replacement of a previously submitted data set.

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/ingest-central#93] opened 2018-08-10 11:07 UTC
**What problem does the suggested enhancement solve? Please describe.**

As an HCA-DCP wrangler I want to be able to trigger a replacement of a previously submitted data set in Phase 1.

**What type of enhancement is this?**

Usability

**How will this enhancement benefit wrangers and/or end-users?**

Allow updates of submitted datasets in case of any changes in the dataset. 

**How complex to implement do you estimate this enhancement will be? (High, Medium, Low)**

Low

**How much benefit do you estimate this enhancement will provide? (High, Medium, Low)**

High

**How urgent is this and is there a specific date it needs to be done by? (High, Medium, Low)**

High - Phase 1

**Describe your preferred solution**

We need to be able to trigger or flag to the data store that a dataset has been replaced or superseded by a new dataset when there have been updates made.

**Describe alternatives you've considered**

**Additional context**

Replaces JIRA HCA-1161.

**Comment by justincc** [comment] 2018-11-12 11:03
'Workaround' is to make a completely new submission

**Comment by hewgreen** [comment] 2018-11-12 15:47
This ticket should not be closed. Wranglers need to be able to update bundles and json docs in the datastore when a new version is pushed.

How complex to implement do you estimate this enhancement will be? (High, Medium, Low)
Should be HIGH rather than low. This is no longer phase 1.

**Comment by justincc** [comment] 2019-05-08 09:56
Dupe of epic.

**Closed by justincc** 2019-05-08 09:56 UTC
