### ISSUE TITLE
Can't upload a spreadsheet in staging

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/ingest-central#505] opened 2019-08-16 10:20 UTC
**Can't upload spreadsheet**

I get the following error when trying to upload a spreadsheet in staging.

**To Reproduce**

1. Go to file upload in the UI 
2. Select the 8ea29906-c23a-4fd9-b765-f0cee2a5c81e Submission uuid from Aug 16, 2019, 11:19:00 AM
4. See an error in a red box

**Expected behaviour**
 
 I expected to the spreadsheet to upload.

**Actual behaviour**

Please explain what actually happened.

Red banner with error.

**Impact**

Please explain how this bug impacts users to help us prioritise.

Example: 

This blocks me from submitting this dataset.

**Screenshots or Messages**

![Screenshot 2019-08-16 at 11 15 16](https://user-images.githubusercontent.com/38244059/63161117-38b9eb00-c017-11e9-801a-36b5d0261880.png)

**Comment by rolando-ebi** [comment] 2019-08-16 13:17
@zperova Are you using pinned schema versions in the schema tab on the spreadsheet?

**Comment by zperova** [comment] 2019-08-16 14:01
Yes, @rolando-ebi  - the list that was generated prior to metadata freeze

**Comment by rdgoite** [comment] 2019-08-16 15:14
This looks like another case of phantom cells in the `Schemas` tab. I tried creating a fresh schemas tab by adding a new one, then copying over only the visible contents of the originally submitted tab (provided by @zperova), removing the original and renaming the new tab `Schemas`. This addressed the reported problem. However, there seems to be another problem with field names in the provided spreadsheet.

**Comment by zperova** [comment] 2019-08-16 15:32
@rdgoite i have fixed that as you have suggested and I do now see the following error:
`ingest.importer.error : 'str' object does not support item assignment`

**Comment by zperova** [comment] 2019-08-16 15:34
do you see any helpful details in the logs?

**Comment by justincc** [comment] 2019-08-21 10:45
Hi @rdgoite. What happened with this?

**Comment by zperova** [comment] 2019-08-21 13:02
@justincc the original problem was solved, however am now on the next importer error that I have not yet decrypted: 
![Screenshot 2019-08-19 at 15 51 49](https://user-images.githubusercontent.com/38244059/63434061-3fcc6900-c41c-11e9-943c-a5025e02403f.png)

**Comment by zperova** [comment] 2019-08-21 13:04
@justincc all this will be solved when this is in place #507

**Comment by MightyAx** [comment] 2019-09-02 15:02
Duplicate of #505
solved by ingest-client#47

**Closed** 2019-09-04 12:58 UTC
Labels: bug
