### ISSUE TITLE
Create a run book for ingest operations

### ISSUE THREAD

**Issue by morrisonnorman** [HumanCellAtlas/ingest-central#133] opened 2018-08-17 13:40 UTC

**Comment by morrisonnorman** [comment] 2018-08-17 13:41
Migrated from JIRA https://www.ebi.ac.uk/panda/jira/browse/HCA-881

**Comment by rdgoite** [comment] 2018-08-29 15:52
I think this is a duplicate of https://app.zenhub.com/workspace/o/humancellatlas/ingest-central/issues/111. Which of the tickets shall we close?

**Comment by justincc** [comment] 2018-11-26 17:20
This one

**Closed by justincc** 2018-11-26 17:20 UTC
