### ISSUE TITLE
Support number type fields in the Importer

### ISSUE THREAD

**Issue by rdgoite** [HumanCellAtlas/ingest-central#302] opened 2019-02-15 10:34 UTC
At the time of writing, Ingest Importer only recognises `integer` as the numeric data type in the metadata schema. Recent changes to the schema have introduced JSON Schema `number` type, which the Importer does not recognise. Fields of `number` type are currently interpreted as string by default.

**Comment by justincc** [comment] 2019-02-15 10:37
@malloryfreeberg @daniwelter This is the ticket for what you were talking about this morning. I presume we're expecting to handle all json schema types?

**Comment by rdgoite** [comment] 2019-02-15 10:48
@hewgreen This is ultimately the reason why the `excitation_wavelength` field was being interpreted as a string.

**Comment by daniwelter** [comment] 2019-02-15 11:07
I checked the JSON schema specs and `number` is not a new type - it has existed since at least draft 4 and we have had `number` fields in our metadata schema for over a year.

**Comment by malloryfreeberg** [comment] 2019-02-15 11:08
> Recent changes to the schema have introduced JSON Schema `number` type

I don't think this is a recent change. At least, it's been a part of the [JSON Schema spec](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.1.1) since version 6.1.1.

**Comment by aaclan-ebi** [comment] 2019-02-18 11:54
Fix is in dev and integration.

staging promotion: 20th Feb
production: 27th Feb

**Comment by justincc** [comment] 2019-02-19 11:34
Dupe of #296

**Closed** 2019-03-01 11:33 UTC
